-- creates a database and a table inside the database
-- query to create db `hbtn_0d_usa` and table `states` inside it
-- id field to be autogenerated, cant be null and is primary key
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS states (
id INT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
name VARCHAR(256) NOT NULL);
