-- script to create a database and a table in the database
-- query to create db `hbtn_0d_usa` and table `cities`
-- id field of `cities` be autogenerated, not null and unique
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS cities (
id INT AUTO_INCREMENT NOT NULL UNIQUE PRIMARY KEY,
state_id INT NOT NULL,
name VARCHAR(256) NOT NULL,
FOREIGN KEY (state_id) REFERENCES states(state_id));
